### ISSUE TITLE
RESQML example problem

### ISSUE THREAD

**Issue by SkivHisink** [F2I-Consulting/fesapi#297] opened 2021-07-25 09:20 UTC
I ran into problems with opening an example in the official program(RESQMLValidator) and I got errors(look at screens). Are the examples given for C ++ and C # given for RESQML or for another format? Are these examples valid? Also I can't open official RESQML example with your C# program.
![1](https://user-images.githubusercontent.com/49669372/126893739-2cf563dc-0257-4bec-a06f-798acb014579.PNG)
![2](https://user-images.githubusercontent.com/49669372/126893743-a1046314-5ded-4c12-889d-bfe46860c7f8.PNG)

**Comment by philippeVerney** [comment] 2021-07-25 12:39
Hi @SkivHisink ,

Thanks for raising this issue.
First comment : the Geosiris RESQMLValidator has not been maintained after release because not funded. I think Geosiris would be happy to maintain/extend it but they don't want it to do it for free. It may (and will) explain some discrepancies between the RESQMLValidator and some EPC which you can see in real world. There is a lot to discuss about it but I cannot do anything except informing everybody about it including Energistics (which I did/do). Please raise your concern to Energistics if you also have one.

Second comment : Geosiris internally works on a new version of their validator (but it is not a public one). It is known to have different results than the initial validator  https://discourse.f2i-consulting.com/t/epc-resqml-validator-error-message/174/7

Looking at your screenshots, especially the second one, it looks that the validator complains about some WITSML (not RESQML) dataobjects which are exported in the EPC document. I am pretty sure that the validator is not prepared for validating multiple MLs in a same EPC document. This is probably the cause of this error (even if it is accepted since you may put whatever you want, as pdf or png for example, in an EPC document, the reader should just ignore it if does not understand it).
I would advise you to tweak the export source code in order not to export non-RESQML dataobjects if you really want to use/check the RESQML validator.

> Also I can't open official RESQML example with your C# program.
It might be cause of an issue which I discovered recently and added last week in the release notes  :  https://github.com/F2I-Consulting/fesapi/releases/tag/v2.1.0.0
I plan to release v2.1.1.0 fixing this issue this coming week. I'll give a try.

**Comment by philippeVerney** [comment] 2021-07-25 12:56
For completeness, another validator issue here : https://discourse.f2i-consulting.com/t/fesapi-example-propertykind-not-found-validated-by-epc-resqmlv2-0-1-editor/158

**Comment by philippeVerney** [comment] 2021-07-26 13:56
I confirm that v2.1.0.0 cannot read the official RESQML example cause of a regression mentioned last week as a known bug in the release notes.
I also confirm that the fix will be part of v2.1.1.0 or v2.2.0.0 (if I got a working latest RESQML2 draft) end of this week.

**Comment by philippeVerney** [comment] 2021-07-26 13:58
I also reported the validator issue to Energistics and Geosiris.
Geosiris may collaborate to provide their new validator. However, it is definitely out of my authority.

**Closed** 2021-07-30 13:15 UTC
Labels: bug

**Comment by philippeVerney** [comment] 2021-07-30 14:04
See https://github.com/F2I-Consulting/fesapi/releases/tag/v2.1.1.0
